name: Build and Attach Spicetify-UI jar to release

on:
  release:
    types: [ published ]

jobs:
  build-and-release:
    name: Build and Attach
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Spicetify-UI jar
        run: |
          mvn clean install compile assembly:single

      - name: Prepare Spicetify-UI jar
        run: |
          $jarFile = Get-ChildItem -Path . -Include spicetify-ui-*.jar -Recurse | Select-Object -First 1
          Move-Item -Path $jarFile.FullName -Destination ./spicetify-ui.jar

      - name: Upload Spicetify-UI jar
        uses: actions/upload-artifact@v2
        with:
          name: spicetify-ui
          path: ./spicetify-ui.jar

      - name: Attach Spicetify-UI jar to release
        uses: actions/upload-release-asset@v1
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./spicetify-ui.jar
          asset_name: spicetify-ui.jar
          asset_content_type: application/java-archive